Centrer circularprogress (mais pas vraiment)
sgmap/inspire pull request #104
Opened 2016-11-17 16:33 UTC by Flightan

2016-11-17 18:22 UTC, tmerlier commented
Pas vraiment je veux bien mais là... 
<img width="841" alt="circular-center" src="https://cloud.githubusercontent.com/assets/7040549/20401980/2bfb9dfa-acfb-11e6-8a10-e9254985a2f4.png">

2016-11-17 18:25 UTC, tmerlier requested changes
Le `CircularProgress` n'est jamais à la même place en fonction des pages. Mais dans tous les cas il n'est jamais au milieu.

![image](https://cloud.githubusercontent.com/assets/7040549/20402086/a1302046-acfb-11e6-8723-5736c0213304.png)

2016-11-17 18:31 UTC, Flightan commented
Oui je l'ai juste fait sur la page catalog. Il va pas se centrer
automagiquement.
On Thu, 17 Nov 2016 at 19:25, Théophile Merlière <notifications@github.com>
wrote:

> *@tmerlier* requested changes on this pull request.
>
> Le CircularProgress n'est jamais à la même place en fonction des pages.
> Mais dans tous les cas il n'est jamais au milieu.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7040549/20402086/a1302046-acfb-11e6-8723-5736c0213304.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sgmap/inspire-next/pull/104#pullrequestreview-9086657>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABaFapKSYwPo_whiBbo9obtkV22zFiIwks5q_JwqgaJpZM4K1hWp>
> .
>

2016-11-21 09:53 UTC, Flightan commented
@tmerlier better?

2016-11-21 09:54 UTC, tmerlier approved these changes

2016-11-21 09:56 UTC, tmerlier commented
Il ne serait pas plus simple de faire un composant qui a le même style et qui est appelé à chaque fois qu'un composant attend une réponse?

Ça éviterai de dupliquer du code?

2016-11-21 10:18 UTC, Flightan commented
Peut-être, peut-être pas ? J'ai pas d'avis.

2016-11-21 10:42 UTC, merged