Add LineChart component
sgmap/inspire pull request #13
Opened 2016-09-20 13:16 UTC by tmerlier

Add a line chart to see the reapers's evolution.
 
This PR fix #12 Harvests Graph

2016-09-21 10:21 UTC, jdesboeufs requested changes

2016-09-21 11:32 UTC, tmerlier commented on src/Section/HarvestsSection/HarvestsSection.js
> +    for (var i = this.state.harvests.length - 1; i >= 0; i--) {
If I reverse `this.state.harvests`, it will be changed. To perform `reverse()` it should copy `this.state.harvests`.

2016-09-21 11:35 UTC, tmerlier commented on src/Section/HarvestsSection/HarvestsSection.js
> +        data[date] = harvest.itemsFound
I have not been not very inspired. This is a table containing the chart data of crops...

Why not `crops`?

2016-09-23 09:46 UTC, jdesboeufs approved these changes

2016-09-23 09:47 UTC, merged