Ajout/suppression de catalogue pour une organisation
sgmap/inspire pull request #170
Opened 2017-01-05 11:25 UTC by tmerlier

<img width="1182" alt="capture d ecran 2017-01-05 a 12 24 24" src="https://cloud.githubusercontent.com/assets/7040549/21679030/f427b4b4-d341-11e6-9889-09a3c14ce794.png">

2017-01-05 11:41 UTC, jdesboeufs requested changes

2017-01-05 11:41 UTC, jdesboeufs commented on src/components/Catalog/SourceCatalogs.js
> +  displayCatalogs() {
Je propose `toggleCatalogList()`

2017-01-05 11:41 UTC, jdesboeufs commented on src/components/Catalog/SourceCatalogs.js
> +      const newCatalogs = [...catalogs, catalogId]
Pas sûr que le tableau soit la meilleure structure pour ça, on pourrait avoir des doublons.

2017-01-05 11:41 UTC, jdesboeufs commented on src/components/Catalog/SourceCatalogs.js
> +      updateCatalogSource(newCatalogs, organizationId)
updateCatalogSources

2017-01-05 11:41 UTC, jdesboeufs commented on src/components/Catalogs/AddCatalogs.js
> +    const filteredCatalogs = filter(this.state.catalogs, catalog => !sourceCatalogs.includes(catalog.id))
À factoriser ;)

2017-01-05 11:41 UTC, jdesboeufs commented on src/fetch/__mocks__/fetch.js
> +  if (!sourceCatalogs || !sourceCatalogs.length || !organizationId) return Promise.reject(new Error('sourceCatalogs and organizationId are required'))
sourceCatalogs peut être vide

2017-01-05 11:41 UTC, jdesboeufs commented on src/fetch/fetch.js
> +  if (!sourceCatalogs || !sourceCatalogs.length || !organizationId) return Promise.reject(new Error('sourceCatalogs and organizationId are required'))
Idem

2017-01-05 11:41 UTC, jdesboeufs commented on src/fetch/fetch.js
> +  return _f(`https://inspire.data.gouv.fr/dgv/api/organizations/${organizationId}`, {
À factoriser

2017-01-05 13:27 UTC, tmerlier commented on src/components/Catalog/SourceCatalogs.js
> +      const newCatalogs = [...catalogs, catalogId]
Le cas est géré avec la condition `if (!catalogs.includes(catalogId))`

2017-01-06 01:13 UTC, jdesboeufs approved these changes

2017-01-06 01:13 UTC, merged