Déconnexion
sgmap/inspire pull request #174
Opened 2017-01-06 01:07 UTC by tmerlier

Ajoute la possibilité de se déconnecter
<img width="1280" alt="capture d ecran 2017-01-06 a 02 05 42" src="https://cloud.githubusercontent.com/assets/7040549/21703780/d1c081e4-d3b4-11e6-8509-484490b0605b.png">

2017-01-06 01:39 UTC, jdesboeufs approved these changes

2017-01-09 10:37 UTC, jdesboeufs requested changes

2017-01-09 10:37 UTC, jdesboeufs commented on src/components/Header/Header.css
> +.log {
log? Pourquoi ce changement ?

2017-01-09 10:37 UTC, jdesboeufs commented on src/components/Header/Header.js
> +    const login = <a className={log} href={logInUrl}>Publier des données</a>
Il manque `encodeURIComponent()`

2017-01-09 10:50 UTC, tmerlier commented on src/components/Header/Header.css
> +.log {
Pour ne pas être entrer en conflit avec la variable `login` présente dans `<Header />`

2017-01-09 12:35 UTC, jdesboeufs commented on src/components/Header/Header.css
> +.log {
C'est très moche. Ça fait penser à des logs.

2017-01-09 12:35 UTC, jdesboeufs approved these changes

2017-01-09 12:38 UTC, merged