Actualise la recherche quand l'historique de navigation change
sgmap/inspire pull request #188
Opened 2017-01-12 16:15 UTC by tmerlier

Fix #176 Bouton précédent non fonctionnel sur les filtres

2017-01-12 16:24 UTC, tmerlier commented
Je cherche toujours une autre solution qui relancerai simplement `parseQuery()` au lieu de recharger la page...

2017-01-12 17:15 UTC, jdesboeufs requested changes
Je bloque pour le moment.
Il faut qu'on trouve mieux car bidouiller l'historique dans un composant c'est moyen.

2017-01-12 17:21 UTC, tmerlier commented
On ne touche pas à l'historique de cette façon. Mais dans tous les cas, je suis d'accord, il faut trouver mieux.

2017-01-18 21:52 UTC, jdesboeufs commented
See #203

2017-01-18 21:52 UTC, closed without merging