Améliore la section téléchargement de données vectorielles
sgmap/inspire pull request #202
Opened 2017-01-18 15:39 UTC by tmerlier

Avant
------
![image](https://cloud.githubusercontent.com/assets/7040549/22070491/84134dcc-dd9c-11e6-9ffb-d06262478df7.png)

Après
-------
<img width="1162" alt="capture d ecran 2017-01-18 a 16 21 09" src="https://cloud.githubusercontent.com/assets/7040549/22070535/a92669e6-dd9c-11e6-898d-474912ac0360.png">

Fix #192 Améliorer la section téléchargement de données vectorielles

2017-01-18 16:35 UTC, Flightan commented
Pas encore vu le code mais c'est bien plus propre !

2017-01-18 22:10 UTC, jdesboeufs requested changes

2017-01-18 22:10 UTC, jdesboeufs commented on src/modules/Datasets/components/Downloads/DownloadDatasets.js
> +import Visualizer from '../Visualizer/Visualizer'
Viewer ;)

2017-01-18 22:10 UTC, jdesboeufs commented on src/modules/Datasets/components/Downloads/__test__/Download.test.js
> +describe.only('<Download />', () => {
BOOM

2017-01-19 07:19 UTC, jdesboeufs approved these changes

2017-01-19 07:22 UTC, merged