Fix #263
sgmap/inspire pull request #264
Opened 2017-02-02 23:03 UTC by jdesboeufs

Affiche les bonnes erreurs.
Mais ce serait mieux dans le futur qu'on traite ce cas en amont.

2017-02-03 09:06 UTC, tmerlier requested changes

2017-02-03 09:06 UTC, tmerlier commented on src/modules/Datasets/components/DatasetTable/DatasetTable.js
> +          noDataText="Les données sont vides" />
Ce message est trompeur, on indique que les données sont vides alors qu'elles sont simplement en cours de chargement.

2017-02-03 10:23 UTC, jdesboeufs commented on src/modules/Datasets/components/DatasetTable/DatasetTable.js
> +          noDataText="Les données sont vides" />
Oui mais dans le cas où elle sont vides on est trompeur aussi.

2017-02-03 11:57 UTC, tmerlier commented on src/modules/Datasets/components/DatasetTable/DatasetTable.js
> +          noDataText="Les données sont vides" />
Il serait préférable de gérer l'erreur en amont comme tu l'as fait pour `PreviewMap`. Le composant `Table ` ne devrait simplement pas être appelé si aucune donnée ne sont présente.

2017-02-03 17:38 UTC, jdesboeufs commented
Donc on ne corrige pas le bug on attend la solution parfaite ? :)
Le ven. 3 févr. 2017 à 12:57, Théophile Merlière <notifications@github.com>
a écrit :

> *@tmerlier* commented on this pull request.
> ------------------------------
>
> In src/modules/Datasets/components/DatasetTable/DatasetTable.js
> <https://github.com/sgmap/inspire/pull/264>:
>
> > @@ -19,7 +19,7 @@ class DatasetTable extends Component {
>            sortable={true}
>            itemsPerPage={20}
>            pageButtonLimit={20}
> -          noDataText="Chargement..." />
> +          noDataText="Les données sont vides" />
>
> Il serait préférable de gérer l'erreur en amont comme tu l'as fait pour
> PreviewMap. Le composant Table ne devrait simplement pas être appelé si
> aucune donnée ne sont présente.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sgmap/inspire/pull/264>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABLJgFzMYYc5tRqNfuUCBVNSr4Po3dteks5rYxY5gaJpZM4L1wK_>
> .
>

2017-02-06 10:28 UTC, tmerlier commented
Je te propose cette solution. Qu'en penses-tu @jdesboeufs ?

2017-02-06 12:01 UTC, jdesboeufs commented
Ça fait le job ! :thumbsup:

2017-02-06 13:06 UTC, tmerlier approved these changes

2017-02-06 13:06 UTC, merged