Copier rapidement un identifiant de jeu de données
sgmap/inspire pull request #282
Opened 2017-02-10 13:52 UTC by tmerlier

Constat
------
Bien qu'à première vu peu utile, il s'est avéré qu'une grande majorité des administrateurs des plateformes utilisé l'identifiant des jeux de données situé en haut de page. Celui-ci est rapidement copier afin d'être utilisé autre part.

Fonctionnalité discrète
----------
Elle n'est volontairement visible que pour les utilisateurs souhaitant copier l'identifiant.

2017-02-10 13:58 UTC, jdesboeufs requested changes
Dépendance inutile, casse la compatibilité avec preact.

2017-02-10 14:06 UTC, jdesboeufs commented
Je précise ma pensée, pourquoi ne pas juste utiliser `copy-to-clipboard`? Quitte à faire notre propre composant adapté de `react-copy-to-clipboard`?

2017-02-10 14:13 UTC, jdesboeufs commented
Pas fan du rendu par ailleurs, c'est quand même pas difficile de copier-coller.
Je crois que l'idée qui circulait hier c'était surtout de cacher cet identifiant, le mettre tout en bas.

2017-02-10 14:15 UTC, tmerlier commented
Je n'ai pas fait attention à la compatibilité avec `preact`. Ça ne me pose aucun problème de le faire avec `copy-to-clipboard`.

Non au contraire, j'ai cru comprendre qu'ils l'utilisent tous parce qu'il est facilement accessible.

2017-02-10 14:16 UTC, jdesboeufs commented
Oui mais les nouveaux utilisateurs qu'on cible ne sont pas les administrateurs, et eux ne comprennent pas ce que c'est.

2017-02-10 14:19 UTC, jdesboeufs commented
J'ai dit des conneries, pas de problème avec `preact` puisqu'il y a `preact-compat`.
Reste juste le rendu qui est bien moche, et peut-être à déplacer l'identifiant ailleurs.

2017-02-10 14:20 UTC, jdesboeufs commented
Mais on peut se dire que le positionnement se fera dans l'Epic de la fiche.
Tu trouves ça évident qu'on puisse copier en cliquant dessus ?

2017-02-10 14:34 UTC, tmerlier commented
Pour les utilisateurs qui copie-colle déjà se sera évidant pour eux car le curseur de la souris change lorsque l'on passe dessus. Une fois cliqué, la mention "Copié !" apparait.

2017-02-10 14:41 UTC, jdesboeufs commented
Il n'y a pas encore d'utilisateurs qui copient-collent, on parle de 3/4 personnes.
Quid des autres administrateurs, quid des utilisateurs non administrateurs.

2017-02-13 21:30 UTC, jdesboeufs commented
Après réflexion je préfèrerai "voir" quelque chose.
C'est pas pour rien si tous les sites mettent soit "Copier" soit http://fontawesome.io/icon/clipboard/

2017-03-02 10:31 UTC, closed without merging