Doughnut chart test
sgmap/inspire pull request #34
Opened 2016-10-14 13:47 UTC by tmerlier

2016-10-14 13:47 UTC, tmerlier commented
@jdesboeufs

2016-10-14 16:50 UTC, jdesboeufs requested changes

2016-10-14 16:50 UTC, jdesboeufs commented on src/Charts/DoughnutChart/DoughnutChart.js
> +  formatData(data) {
`formatData` and `setColor` have nonbenefit to be attached to the component. You can use pure function.

2016-10-17 08:20 UTC, jdesboeufs approved these changes

2016-10-17 08:22 UTC, merged