Histogram
sgmap/inspire pull request #35
Opened 2016-10-14 15:01 UTC by tmerlier

It appeared that **LineChart** and **BarChart** components were completely **identical**.
This new **Histogram** component allows to merge by choosing the plot.

2016-10-14 15:02 UTC, tmerlier commented
@jdesboeufs

2016-10-14 16:55 UTC, jdesboeufs requested changes

2016-10-14 16:55 UTC, jdesboeufs commented on src/Charts/Histogram/Histogram.js
> +  formatData(data) {
No need to attach this helper to the component ;)

2016-10-17 08:19 UTC, jdesboeufs approved these changes

2016-10-17 08:21 UTC, merged