Complète la fiche de jeu de donnée avec de nouvelles informations
sgmap/inspire pull request #354
Opened 2017-03-24 10:22 UTC by tmerlier

### Entête du jeu de donnée
- La description de la donnée n'est désormais affichée que partiellement. Un bouton `Afficher la suite` permet de l'afficher dans son intégralité et de la refermer.
- Ajout de la raison d'être du jeu de données (`purpose`)

### Section Informations techniques
- Ajout de la catégorie thématique du jeu de donnée (`topicCategories`) 

### Nouvelle section Contributions
Celle nouvelle section affiche les différentes contributions/partitions (`credit`) apportées au jeu de données.
<img width="372" alt="capture d ecran 2017-03-24 a 11 22 12" src="https://cloud.githubusercontent.com/assets/7040549/24290146/2b2f29cc-1084-11e7-9a6d-9e52e305bfac.png">

### Nouvelle section `Licence`
Cette nouvelle section a pour objectif de présenter la license utilisée quand celle-ci est disponible. Elle donne la description de la license mais résume également les permissions, conditions et limitations que celle-ci implique.
<img width="841" alt="capture d ecran 2017-03-24 a 11 08 14" src="https://cloud.githubusercontent.com/assets/7040549/24289593/3639aef2-1082-11e7-9cc0-6a31d8c4bc53.png">

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/dataGouvChecks.js
> +    url: 'https://www.etalab.gouv.fr/licence-ouverte-une-nouvelle-mouture-pour-anticiper-le-cadre-legal-a-venir',
Mauvaise adresse

2017-03-24 11:38 UTC, jdesboeufs commented on src/fetch/__test__/dataset.json
> +    "license":null,
Pourquoi ?

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  imageryBaseMapsEarthCover: 'Imagerie',
imagerie, fonds de cartes, occupation de sols

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  climatologyMeteorologyAtmosphere: 'climatologie météorologie atmosphère',
climatologie, météorologie, athmosphère

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  biota: 'biota',
biote

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  utilitiesCommunication: 'utilitaires communication',
services d'utilité publique, communication

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  planningCadastre: 'planification du cadastre',
cadastre, planification

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  elevation: 'élévation',
altitude

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  intelligenceMilitary: 'intelligence militaire',
infrastructures militaires

2017-03-24 11:38 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  location: 'emplacement',
localisation

2017-03-24 11:40 UTC, jdesboeufs commented on src/helpers/dataGouvChecks.js
> +    url: 'https://www.etalab.gouv.fr/licence-ouverte-une-nouvelle-mouture-pour-anticiper-le-cadre-legal-a-venir',
https://www.etalab.gouv.fr/licence-ouverte-open-licence

2017-03-24 12:12 UTC, tmerlier commented on src/fetch/__test__/dataset.json
> +    "license":null,
J'ai mis à jour ce faux dataset avec un vrai. Je suppose que j'avais triché sur la licence ;) Je remets ça.

2017-03-27 17:29 UTC, jdesboeufs requested changes

2017-03-27 17:29 UTC, jdesboeufs commented on src/helpers/status.js
> +  obsolete: {status: 'obsolète', consequences: 'Attention, il est possible que cette fiche ne soit plus à jour et présente des données obsolètes.'},
Le "attention" est inutile, il devrait faire parti du template.
Pourquoi dire "il est possible" alors qu'on en est sûr ?

2017-03-27 17:29 UTC, jdesboeufs commented on src/helpers/status.js
> +  historicalArchive: {status: 'archive historique'},
Pourquoi ne pas avoir suivi le tableau proposé ?

2017-03-27 17:29 UTC, jdesboeufs commented on src/helpers/status.js
> +  historicalArchive: {status: 'archive historique'},
https://github.com/sgmap/inspire/issues/350#issuecomment-288862953

2017-03-27 17:29 UTC, jdesboeufs commented on src/helpers/status.js
> +  underDevelopment: {status: 'en cours de développement', consequences: 'Attention, il est possible que certaines données soient erronées ou subisse des changements.'},
Pareil. + faute de grammaire

2017-03-27 17:29 UTC, jdesboeufs commented on src/helpers/topicCategories.js
> +  imageryBaseMapsEarthCover: 'imagerie, fonds de cartes, occupation de sols',
occupation des sols

2017-03-27 17:29 UTC, jdesboeufs commented on src/modules/Datasets/components/DatasetSection/DatasetSection.js
> +              <div>Licence : <span>{license || 'non déterminé'}</span></div>
non déterminée.
Par ailleurs ça mérite un mapping et des liens :

* fr-lo => [Licence Ouverte](https://www.etalab.gouv.fr/licence-ouverte-open-licence)
* fr-loa => [Licence Ouverte Administrations](https://www.etalab.gouv.fr/nouvelle-licence-pour-la-reutilisation-des-informations-publiques-elements-de-clarification)
* odbl => [Open Database License (ODbL 1.0)](https://vvlibri.org/fr/licence/odbl/10/fr)

2017-03-27 17:29 UTC, jdesboeufs commented on src/modules/Datasets/components/TechnicalInformations/TechnicalInformations.js
> +          <div>Catégorie du jeu de données : <b>{topicCategories[topicCategory] || 'Non renseignée'}</b></div>
Pas homogène : non renseigné

2017-03-27 17:29 UTC, jdesboeufs commented on src/modules/Datasets/components/TechnicalInformations/TechnicalInformations.js
>            <div>Licence : <b>{license || 'non déterminé'}</b></div>
non déterminée. Cf ci-dessus

2017-03-27 17:29 UTC, jdesboeufs commented
Un peu violent le warning. Google ne pas pas beaucoup apprécier niveau SEO.

2017-03-28 08:04 UTC, tmerlier commented on src/modules/Datasets/components/DatasetSection/DatasetSection.js
> +              <div>Licence : <span>{license || 'non déterminé'}</span></div>
Tu souhaites qu'on liste les différentes licences possible lorsque celle-ci n'est pas déterminée ?

2017-03-28 08:05 UTC, tmerlier commented on src/helpers/status.js
> +  historicalArchive: {status: 'archive historique'},
My bad ! Je ne m'en étais pas aperçu.

2017-03-28 08:09 UTC, tmerlier commented
Il reste le titre de la fiche qui est probablement le plus importe concernant le SEO. De plus, le fait qu'une fiche remonte moins bien lorsqu'elle est obsolète ou archivée n'est peut-être pas si mal... Non ?

2017-03-28 08:35 UTC, jdesboeufs commented on src/modules/Datasets/components/DatasetSection/DatasetSection.js
> +              <div>Licence : <span>{license || 'non déterminé'}</span></div>
Oui mais cette PR est gelée, donc avançons quand même ;)

2017-03-28 08:36 UTC, jdesboeufs commented
OK pour tester, on verra bien les retours.

2017-03-28 14:17 UTC, tmerlier commented
cc @jdesboeufs modif' effectuées et nouvel visuel du `warning` mis à jour dans le résumé de la PR.

2017-03-28 14:41 UTC, jdesboeufs approved these changes

2017-03-28 14:47 UTC, merged

2017-03-28 14:48 UTC, jdesboeufs commented
🍾