CatalogDetail Tests
sgmap/inspire pull request #36
Opened 2016-10-17 09:37 UTC by tmerlier

2016-10-17 09:38 UTC, tmerlier commented
@jdesboeufs

2016-10-17 09:59 UTC, jdesboeufs requested changes

2016-10-17 09:59 UTC, jdesboeufs commented on src/CatalogDetail/CatalogDetail.js
>      this.state = {catalog: undefined, metrics: undefined}
Bad practice.
Consider using `getInitialState()`.
Moreover setting values to `undefined` can be easily work-arounded.

2016-10-17 09:59 UTC, jdesboeufs commented on src/CatalogDetail/CatalogDetail.js
> +import fetchCatalog from '../fetch/fetchCatalog'
In the future, those functions could be grouped in a module.

2016-10-17 09:59 UTC, jdesboeufs commented on src/CatalogDetail/CatalogDetail.js
> +    return fetchCatalog(this.props.params.catalogId)
The two `fetch` can be processed in parallel. Consider using `Promise.all`.
You should break this into two component methods: one for Catalog, one for Metrics.

2016-10-17 09:59 UTC, jdesboeufs commented on src/CatalogDetail/CatalogDetail.js
> +      .catch(err => console.error(err));
`console.error` is a bad practice since the final user has no access to console.

2016-10-17 16:40 UTC, tmerlier commented
@jdesboeufs

2016-10-18 10:04 UTC, jdesboeufs approved these changes

2016-10-18 10:14 UTC, merged