Suppression atelier #6 et ajout atelier #7
sgmap/inspire pull request #385
Opened 2017-04-20 10:19 UTC by mariondr

sur inspire.data.gouv.fr/events

2017-04-20 10:22 UTC, tmerlier approved these changes

2017-04-20 12:36 UTC, jdesboeufs commented
Il faut aussi ajouter l'atelier 5 dans les anciens.

2017-04-20 12:54 UTC, tmerlier requested changes
Ajouter dans `pastEvents ` ==>
`{name: 'Atelier #5', date: '18/04/2017', link: ''}`

2017-04-21 08:57 UTC, tmerlier approved these changes

2017-04-21 08:58 UTC, tmerlier commented
@jdesboeufs `As an administrator, you may still merge this pull request.`
![image](https://cloud.githubusercontent.com/assets/7040549/25270584/6fca0f44-2681-11e7-9f8d-471f28aede16.png)

2017-04-21 12:46 UTC, merged