Internationalisation avec i18next (Partie 1)
sgmap/inspire pull request #415
Opened 2017-07-25 14:09 UTC by tmerlier

**Composants**:
- Header
- HomePage
- Footer

**Modules**:
- Catalogs

**Nouvelle fonctionnalité**:
- Possibilité de changer la langue anglais/français

2017-07-27 14:34 UTC, tmerlier commented
cc @jdesboeufs @tusbar

2017-07-27 18:52 UTC, tusbar requested changes

2017-07-27 18:52 UTC, tusbar commented on src/components/CatalogPreview/__test__/CatalogPreview.test.js
> +      wrapper = mount(<CatalogPreview catalog={catalog} />, {context})
`{ context }`

2017-07-27 18:52 UTC, tusbar commented on src/components/CatalogPreview/__test__/ObsoleteWarning.test.js
> +import {ObsoleteWarning} from '../ObsoleteWarning'
`{ ObsoleteWarning }`

2017-07-27 18:52 UTC, tusbar commented on src/components/CatalogPreview/__test__/ObsoleteWarning.test.js
> +const t = k => k
Can you give it a better nam? Like `translateMock`, so we can understand easily.

2017-07-27 18:52 UTC, tusbar commented on src/components/Charts/DoughnutChart/DoughnutChart.js
> +    labels: labels.map(label => (t(label))),
Parens not needed: `.map(label -> t(label))`

2017-07-27 18:52 UTC, tusbar commented on src/components/Charts/DoughnutChart/DoughnutChartTrad.json
> +    "no_data": "Aucune donnée",
`noData`?

2017-07-27 18:52 UTC, tusbar commented on src/components/Charts/DoughnutChart/__test__/DoughnutChart.test.js
> +const t = k => k
Same thing here.

2017-07-27 18:52 UTC, tusbar commented on src/components/Charts/Histogram/__test__/Histogram.test.js
> +const t = k => k
And here

2017-07-27 18:52 UTC, tusbar commented on src/components/LanguageSelection/LanguageSelection.js
> +import style from './LanguageSelection.scss'
I usually call the imported CSS modules `styles`, not `style`. Just for consistency. :)

2017-07-27 18:52 UTC, tusbar commented on src/components/LanguageSelection/LanguageSelection.js
> +import React, { Component } from 'react'
Just `import React from 'react'` and use `React.Component`

2017-07-27 18:52 UTC, tusbar commented on src/components/LanguageSelection/LanguageSelection.js
> +class LanguageSelection extends Component {
This can be a `PureComponent` I believe, the HOC will update `language`, triggering the render.

2017-07-27 18:52 UTC, tusbar commented on src/components/LanguageSelection/LanguageSelection.scss
> +select {
Use classes! This updates the global `select` style for the whole app.

2017-07-27 18:52 UTC, tusbar commented on src/helpers/doneSince.js
> +    moment.locale(language)
This shouldn’t be done here. But whenever the language is changed.

2017-07-27 18:52 UTC, tusbar commented on src/helpers/doneSince.js
> +export function doneSince(endTime, language = 'en') {
This method should be locale/language agnostic.

2017-07-27 18:52 UTC, tusbar commented on src/routes/Catalogs/routes/Catalog/components/CatalogHarvestsRow/CatalogHarvestsRow.js
> +      {doneSince(harvest.finished, i18n.language)}
Let’s not use this here :)

2017-07-27 18:52 UTC, tusbar commented on src/routes/Catalogs/routes/CatalogHarvest/components/CatalogHarvestView/CatalogHarvestViewTrad.json
> +{
Should this file be removed?

2017-07-27 18:52 UTC, tusbar commented on src/routes/NotFound/components/NotFoundPage/NotFoundPageTrad.json
> +{
Do we need this file?

2017-07-27 19:31 UTC, jdesboeufs commented on src/components/CatalogPreview/__test__/CatalogPreview.test.js
> +      wrapper = mount(<CatalogPreview catalog={catalog} />, {context})
Maybe we could enable the appropriate ESLint rule

2017-07-27 19:35 UTC, jdesboeufs submitted a review, later dismissed

2017-07-27 19:35 UTC, jdesboeufs commented on src/components/Charts/DoughnutChart/DoughnutChartTrad.json
> +    "no_data": "Aucune donnée",
Yep

2017-07-27 19:35 UTC, jdesboeufs commented on src/components/Charts/DoughnutChart/DoughnutChartTrad.json
> +    "nonGeographicDataset": "jeu de données non géographique",
géographique**s**

2017-07-27 19:35 UTC, jdesboeufs commented on src/components/Charts/DoughnutChart/DoughnutChartTrad.json
> +    "grid": "grid"
The Grid™

2017-07-27 19:35 UTC, tusbar commented on src/components/CatalogPreview/__test__/CatalogPreview.test.js
> +      wrapper = mount(<CatalogPreview catalog={catalog} />, {context})
@jdesboeufs it’s coming :)

2017-07-28 09:01 UTC, tmerlier commented
@tusbar 2 round

2017-07-31 13:21 UTC, tusbar approved these changes

2017-07-31 13:29 UTC, merged