Internationalisation de Dataset (I18next part2)
sgmap/inspire pull request #427
Opened 2017-08-04 15:38 UTC by tmerlier

2017-08-04 17:12 UTC, tusbar commented on src/locales/en.json
> +    "dgvPublication": "Published on data.gouv.fr",
pourquoi celui la commence avec une majuscule et pas les autres?

2017-08-04 17:17 UTC, tusbar requested changes

2017-08-04 17:17 UTC, tusbar commented on src/locales/fr.json
> +  "dataTypes": {
C’est dommage d’avoir ça au même titre que les composants

2017-08-04 17:17 UTC, tusbar commented on src/routes/Dataset/components/DatasetDataGouvPublication/DatasetDataGouvPublication.js
> +          <Interpolate i18nKey='DatasetDataGouvPublication.cantBePublished'
`Trans` ne fonctionne toujours pas avec la derniere version?

2017-08-04 17:17 UTC, tusbar commented on src/routes/Dataset/index.js
> +        resources: await import(/* webpackMode: 'lazy-once', webpackChunkName: 'catalogs' */ `./locales/${lang}.json`)
`dataset`, not `catalogs`

2017-08-07 08:52 UTC, tmerlier commented on src/locales/fr.json
> +  "dataTypes": {
Comment organiserais tu le fichier ?

2017-08-07 09:04 UTC, tmerlier commented on src/components/Footer/Footer.js
> +        <Trans i18nKey='Footer.madeBy'>
Utilisation de `Trans` est plus approprié mais je trouve `Interpolate` plus élégante dans ce cas ci.

2017-08-07 10:18 UTC, tusbar commented on src/locales/fr.json
> +  "dataTypes": {
Je sais pas je commencerais par un 
```
{
  "components": {
    "Loader": {}
  },
  "enums": {
    "dataTypes": {}
  }
}
```

2017-08-07 10:19 UTC, tusbar commented on src/components/Footer/Footer.js
> +        <Trans i18nKey='Footer.madeBy'>
C'était pas gênant interpolate ici

2017-08-07 10:27 UTC, tmerlier commented on src/locales/fr.json
> +  "dataTypes": {
On risque d'avoir des `namespace` à rallonge comme `components.Composent.trad` ou alors on doit changer partout `translate(Namespace.components)`

2017-08-07 10:28 UTC, tusbar commented on src/locales/fr.json
> +  "dataTypes": {
c'est pas un namespace mais une subproperty, donc non tu ne peux pas `translate('Common.components')`

2017-08-07 10:29 UTC, tusbar commented on src/locales/fr.json
> +  "dataTypes": {
Ça rajouts 11 caractères aux keys de `Common`, c'est pas la mort non plus

2017-08-07 10:36 UTC, tusbar commented on src/components/Footer/Footer.js
> +        <Trans i18nKey='Footer.madeBy'>
Je pense faudra faire un ticket/PR chez react-i18next, c'est quand même étrange de compter 2 fois les balises.

2017-08-07 12:53 UTC, tmerlier commented
cc @tusbar

2017-08-07 16:59 UTC, tusbar commented on src/components/Charts/DoughnutChart/DoughnutChart.js
> +    labels: labels.map(label => t(`components.DoughnutChart.${label}`)),
shouldn't those be some sort of enums?

2017-08-07 17:00 UTC, tusbar commented on src/components/Charts/DoughnutChart/DoughnutChart.js
> +    labels: labels.map(label => t(`components.DoughnutChart.${label}`)),
genre dataTypes?

2017-08-07 17:04 UTC, tusbar commented on src/routes/Dataset/index.js
> +    i18n.languages.forEach(async lang => {
`i18n.availableLanguages.forEach(`

2017-08-07 17:04 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "distributionAvailable": "At least one of the distribution is available.",
At least one of the distribution*s*

2017-08-07 17:07 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "unrecognizedLicense": "The {{ license }} license is not recognized.",
The {{ license }} license was not recognized.

2017-08-07 17:17 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "objectif": "Objectif",
"purpose": "Purpose",

2017-08-07 17:17 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "dataOrigin": "Origin of data"
Data origin

2017-08-07 17:18 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "lifeCycleTitle": "Data life cycle (by producer)",
Data life cycle (according to producer)

2017-08-07 17:18 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "frequencyUpdate": "Frequency update",
"updateFrequency": "Update frequency"

2017-08-07 17:18 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "topicCategory": "Category of the dataset",
Dataset category

2017-08-07 17:18 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "otherTitle": "Other informations",
Other information

2017-08-07 17:19 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "scale": "Scalle",
Scale

2017-08-07 17:19 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +      "obsoleteWarning": "Attention this dataset is considered as {{status}} by its producer",
This dataset is considered {{status}} by its producer

2017-08-07 17:20 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +        "technicalInformations": "Technical Informations",
"technicalInformation": "Technical Information"

2017-08-07 17:21 UTC, tusbar commented on src/routes/Dataset/locales/en.json
> +        "preview": "Preview data",
Data preview

2017-08-07 17:22 UTC, tusbar commented on src/routes/Dataset/locales/fr.json
> +      "objectif": "Objectif",
"purpose": "Objectif"

2017-08-07 17:22 UTC, tusbar commented on src/routes/Dataset/locales/fr.json
> +      "frequencyUpdate": "Fréquence de mise à jour",
"updateFrequency": "Fréquence de mise à jour"

2017-08-07 17:23 UTC, tusbar commented on src/routes/Dataset/locales/fr.json
> +        "technicalInformations": "Informations techniques",
"technicalInformation": "Informations techniques"

2017-08-08 07:48 UTC, tmerlier commented on src/components/Charts/DoughnutChart/DoughnutChart.js
> +    labels: labels.map(label => t(`components.DoughnutChart.${label}`)),
Pas vraiment car c'est un mélange de types de données, de formats et autre. En revanche `Filter` s'y prête mieux mais pour le moment, il y est le seul composant à les utiliser.

2017-08-08 07:52 UTC, tmerlier commented on src/routes/Dataset/locales/fr.json
> +        "technicalInformations": "Informations techniques",
Pourquoi cette différence de pluriel/singulier entre l'anglais et le français ?

2017-08-08 09:02 UTC, tusbar commented on src/routes/Dataset/locales/fr.json
> +        "technicalInformations": "Informations techniques",
Parce que en anglais, `information` ne prend pas de s, c’est un nom non-quantifiable, donc singulier et pluriel par défaut.

2017-08-08 11:58 UTC, merged