Replace DocumentTitle by Helmet [WIP]
sgmap/inspire pull request #441
Opened 2017-08-10 09:11 UTC by tmerlier

2017-08-11 13:42 UTC, tusbar requested changes

2017-08-11 13:42 UTC, tusbar commented on src/components/App.js
> +              <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/components/reset.min.css' />
all these things that don’t change should stay in index.html, we should only keep the things that can change when navigating to a new route in here

2017-08-11 13:42 UTC, tusbar commented on src/components/App.js
> +            <Helmet defaultTitle='inspire.data.gouv.fr'>
you can add a `titleTemplate` here like `'%s | inspire.data.gouv.fr'`, so when in sub components you set `title='Foo'`, the title will be `<title>Foo | inspire.data.gouv.fr</title>`

2017-08-11 13:42 UTC, tusbar commented on src/components/App.js
> +            <Helmet defaultTitle='inspire.data.gouv.fr'>
Also, you can even have sub title templates, like on twitter.com

For example on a search page:

```js
<Helmet
  titleTemplate='%s | Twitter Search'
  defaultTitle='Twitter Search'
  title={query.q}
/>
```

2017-08-11 13:42 UTC, tusbar commented on src/routes/NotFound/components/NotFoundPage/NotFoundPage.js
> +    <Helmet title={'Erreur 404'} />
Shouldn’t there be a translation string for this? :)

2017-08-21 15:54 UTC, tusbar commented on project.config.js
> +    'react-chartjs-2',
no we don’t want this in here

2017-08-22 13:07 UTC, tmerlier commented
cc @tusbar

2017-08-22 22:45 UTC, tusbar commented on project.config.js
>      'react-i18next',
can you add react-helmet in this?

2017-08-22 22:48 UTC, tusbar commented
As I was saying, could you add a default title + template in App component?

Something like

```jsx
<Helmet titleTemplate='%s | inspire.data.gouv.fr' defaultTitle='inspire.data.gouv.fr' />
```

If that’s what we want the website name to be.

2017-08-22 22:49 UTC, tusbar commented on src/routes/Home/components/HomePage/HomePage.js
> +        <Helmet title={t('HomePage.home')} />
If we have a title+default title in <App /> we don’t need a specific title in the home page.

2017-08-23 09:51 UTC, tusbar commented on src/routes/Dataset/components/DatasetView/DatasetView.js
> +      thumbnailUrl = `https://inspire.data.gouv.fr/api/geogw/records/${dataset.recordId}/thumbnails/${dataset.metadata.thumbnails[0].originalUrlHash}`
it’d make more sense so have something like 

```jsx
const hasThumbnails = dataset.metadata.thumbnails && dataset.metadata.thumbnails.length > 0
```

The thumbnailUrl check for the `<DatasetBlock />` doesn’t make a lot of sense

2017-08-23 16:03 UTC, tusbar commented on src/routes/Catalogs/routes/CatalogsList/components/CatalogsListPage/CatalogsListPage.js
> +      <Helmet title={t('CatalogsListPage.documentTitle')}>
I’m not sure Helmet works with children, does it?

2017-08-23 16:04 UTC, tusbar commented on src/routes/Events/components/EventsPage/EventsPage.js
> +  <div>
Here (and in other files as well) we don’t need to add an extra div :)

It’ll work fine under the `<div className={styles.events}>`

2017-08-23 16:05 UTC, tusbar commented on src/components/Errors/Errors.js
> +    <div>
we don’t need the extra div here

2017-08-23 16:06 UTC, tusbar commented on src/modules/Publication/components/Layout/Layout.js
> +    <div>
extra div is not necessary

2017-08-23 16:06 UTC, tusbar commented on src/modules/Publication/components/Organizations/Organizations.js
> +    <div>
extra div is not necessary

2017-08-23 16:06 UTC, tusbar commented on src/routes/Catalogs/routes/Catalog/components/CatalogView/CatalogView.js
> +      <div>
extra div is not necessary

2017-08-23 16:06 UTC, tusbar commented on src/routes/Catalogs/routes/CatalogHarvest/components/CatalogHarvestView/CatalogHarvestView.js
> +    <div>
extra div is not necessary

2017-08-23 16:07 UTC, tusbar commented on src/routes/Dataset/components/DatasetView/DatasetView.js
> +      <div>
extra div not necessary!

2017-08-23 16:07 UTC, tusbar commented on src/routes/NotFound/components/NotFoundPage/NotFoundPage.js
> +  <div>
extra div not necessary

2017-08-23 16:40 UTC, tmerlier commented on src/routes/Catalogs/routes/CatalogsList/components/CatalogsListPage/CatalogsListPage.js
> +      <Helmet title={t('CatalogsListPage.documentTitle')}>
it does.

2017-08-23 16:44 UTC, tmerlier commented on src/routes/Events/components/EventsPage/EventsPage.js
> +  <div>
Two solution:

1. Remove unnecessary `div` and put `Helmet` inside
2.
```
<Helmet>
    {children}
</Helmet>
```

what do you prefer?

2017-08-23 16:58 UTC, tusbar commented on src/routes/Events/components/EventsPage/EventsPage.js
> +  <div>
Helmet children are used to override <head/> properties, it's better to use a self closing component

2017-08-23 16:58 UTC, tusbar commented on src/routes/Events/components/EventsPage/EventsPage.js
> +  <div>
Also, it will remove a lot of useless divs

2017-08-23 17:30 UTC, tusbar commented on src/routes/Catalogs/routes/CatalogsList/components/CatalogsListPage/CatalogsListPage.js
> +      <Helmet title={t('CatalogsListPage.documentTitle')}>
no it doesn't: https://geodatagouv-pr-441.herokuapp.com/catalogs

2017-08-24 08:15 UTC, tusbar commented on src/routes/Dataset/components/DatasetView/DatasetView.js
> +          { hasThumbnails && <meta name='twitter:image' content={`https://inspire.data.gouv.fr/api/geogw/records/${dataset.recordId}/thumbnails/${dataset.metadata.thumbnails[0].originalUrlHash}`} />}
use
```
const { INSPIRE_API_URL } = process.env
```
below imports

and replace this with 

```jsx
{ hasThumbnails && (
  <meta name='twitter:image' content={`${INSPIRE_API_URL}/records/${dataset.recordId}/thumbnails/${dataset.metadata.thumbnails[0].originalUrlHash}`} />
)}
```

2017-08-24 08:16 UTC, tusbar requested changes

2017-08-24 08:16 UTC, tusbar commented on src/routes/Dataset/components/DatasetView/DatasetView.js
> +          { hasThumbnails && <meta name='og:image' content={`https://inspire.data.gouv.fr/api/geogw/records/${dataset.recordId}/thumbnails/${dataset.metadata.thumbnails[0].originalUrlHash}`} />}
same as above

2017-08-24 08:17 UTC, tusbar commented on src/routes/Dataset/components/DatasetView/DatasetView.js
> +          { hasThumbnails && <meta name='twitter:image' content={`https://inspire.data.gouv.fr/api/geogw/records/${dataset.recordId}/thumbnails/${dataset.metadata.thumbnails[0].originalUrlHash}`} />}
(no space, parens and newline)

2017-08-24 09:08 UTC, tusbar approved these changes

2017-08-24 09:12 UTC, merged