Dataset detail
sgmap/inspire pull request #57
Opened 2016-10-25 13:51 UTC by tmerlier

- Translation
- Display catalogs name
- OrganizationsSection
- Lineage

2016-10-25 13:54 UTC, tmerlier commented
Instead of getting all the catalogs and then sort them. We can also ensure CatalogsSection fetch only the good one.

2016-10-25 14:35 UTC, jdesboeufs requested changes

2016-10-25 14:35 UTC, jdesboeufs commented on src/components/Dataset/CatalogsSection.js
> +      cursor: 'pointer',
Is it required?

2016-10-25 14:35 UTC, jdesboeufs commented on src/components/Dataset/DatasetDetail.js
> +    return waitForDataAndSetState(fetchCatalogs(this.props.params.datasetId), this, 'catalogs')
`datasetId` is not required here

2016-10-25 14:35 UTC, jdesboeufs commented on src/components/Dataset/DatasetDetail.js
> +              return dataset.catalogs.includes(catalog.id)
You can use a simple one-liner (drop return instruction)

2016-10-25 14:35 UTC, jdesboeufs commented on src/components/Dataset/DatasetSection.js
> +      <div>Origin of data : <span>{dataset.metadata.lineage}</span></div>
Ugly and wrong place :p

2016-10-25 14:35 UTC, jdesboeufs commented on src/components/Dataset/LinksSection.js
> +    link: {
Same question

2016-10-25 14:36 UTC, tmerlier commented on src/components/Dataset/CatalogsSection.js
> +      cursor: 'pointer',
Yes if the cursor does not change

2016-10-25 14:50 UTC, tmerlier commented
@jdesboeufs

2016-10-26 12:15 UTC, jdesboeufs approved these changes

2016-10-26 12:17 UTC, merged