Ajout d'une checklist pour Dataset
sgmap/inspire pull request #95
Opened 2016-11-14 16:25 UTC by tmerlier

Ajoute une checklist listant les critères à validé pour être publié sur data.gouv.fr.
Cette amélioration a pour but d'aider les producteurs de données à étudier pourquoi leurs données ne pouvaient pas être publiées en tant que données ouvertes.

2016-11-14 17:52 UTC, tmerlier commented
@jdesboeufs

2016-11-14 21:07 UTC, jdesboeufs requested changes

2016-11-15 09:04 UTC, jdesboeufs commented on src/components/Dataset/DatasetChecklist.js
> +    let valid = _checkArray(this.props.dataset.distributions)
const

2016-11-15 09:04 UTC, jdesboeufs commented on src/components/Dataset/DatasetChecklist.js
> +    let valid = _checkArray(this.props.dataset.organizations)
const

2016-11-15 10:31 UTC, jdesboeufs approved these changes

2016-11-15 10:31 UTC, jdesboeufs commented
Ne pas merger pour le moment.
Il manque encore des choses.

2016-11-16 09:54 UTC, Flightan requested changes

2016-11-16 09:54 UTC, Flightan commented on src/components/Checks/CheckDataAvailability.js
> +class CheckLicense extends Component {
CheckDataAvailability

2016-11-16 09:54 UTC, Flightan commented on src/components/Checks/CheckLicense.js
> +      msg = `La licence ${license} n'est pas reconnue.`
Pourquoi ne pas indiquer la liste exhaustive des licences reconnues ?

2016-11-16 10:22 UTC, Flightan approved these changes

2016-11-16 10:29 UTC, merged